### ISSUE TITLE
Support opensearch

### ISSUE THREAD

**Issue by sbrl** [sbrl/Pepperminty-Wiki#112]
If we supported [Opensearch](http://www.opensearch.org/Home), then users would be able to search a wiki from their address bar, which would be seriously cool.

We should look into this to work out how hard it would be to implement.

**Comment by sbrl** [comment]
Ewwww that link has all sorts of hard things in it! O.o I don't really want to rewrite the search engine to optionally return the results in XML....! That would add a lot of bloat to Pepperminty Wiki at best.

[This page](http://www.chromium.org/tab-to-search) looks like it's much easier to implement and easier to understand.

**Comment by sbrl** [comment]
Another relevant link: http://www.opensearch.org/Specifications/OpenSearch/1.1

**Comment by sbrl** [comment]
I've attempted this, but doesn't appear to be working correctly :confused:

If anyone can help, that would be great!

**Comment by ikisler** [comment]
I can't test this due to work limitations, but could this not be working because your wiki address always includes a path?

According to [this page you link to above](http://www.chromium.org/tab-to-search):
- For 1 and 2 Chromium only adds sites that the user navigated to **without a path**. For example http://mysite.com, but not http://mysite.com/foo.

In my case, I always have a URL of https://domain.com/me/whatever/wiki, so I think opensearch will not work using this method?

**Comment by sbrl** [comment]
Ahhhhh. I think you may be right! I'll take a look at fiddling with the core to remove that pesky path then. 
Thanks!

**Comment by sbrl** [comment]
After a bit of fiddling, it's now working! Hooray! Thanks for the help. Turns out I just needed to take a break and come back to it with a fresh mind. And fight with the build system a bit. I should refactor it a bit.....

**Comment by sbrl** [comment]
I've also added your PR's to the changelog & you to the credits, @ikisler. Thanks again! :smiley_cat:
