### ISSUE TITLE
Markdown support in media captions

### ISSUE THREAD

**Issue by SeanFromIT** [sbrl/Pepperminty-Wiki#184]
It appears both HTML tags and markdown are ignored for image captions. It would be nice to process the caption text as markdown before display.

Use cases I'm thinking of:
bold
line breaks

**Comment by sbrl** [comment]
It took me a moment to realise what you meant, but that sounds like a great feature!

We should already have support for recursively parsing because of templating support.

Just to check, you mean adding markdown support to image captions in the `![Caption here](url here)` syntax?

We already have a custom implementation of that actually 'cause of some extra syntax I've added, so it shouldn't be too tough to add (though you'll need to trigger the custom implementation by doing `![caption](url | float_direction)` or `![caption](url | float_direction | size)` - `![caption](url)` won't work on it's own without modification - note to self).

**Comment by sbrl** [comment]
I'm running on the assumption that my previous comment is the correct assumption - this is not implemented!

Regarding the custom image implementation - we don't need to worry about this because you have to trigger it to use the `.... | caption )` bit to get the caption to display in the first place.

Sorted!
