### ISSUE TITLE
Feature request: Click on a search suggestion, go to that page.

### ISSUE THREAD

**Issue by virtadpt** [sbrl/Pepperminty-Wiki#195]
Right now, if you search on something in the wiki, the search box will turn up a number of possible search hits if there are any in a little drop-down below the search box.  If you click on one of them, it populates the search box with the possible search hit.  It seems a bit counter-intuitive to search on something that you just found out exists.  Maybe make it so that clicking on that auto-suggested search hit will take the user right to that page?

**Comment by sbrl** [comment]
Great idea! Unfortunately because this is done via a `<datalist>` element, I don't think that the browser gives me the right event to detect when you select an element from the dropdown list, making this a bit of a challenge to implement.

If you know of such an event that some JS could listen for, then I'm all ears :D

Additionally, it's not currently possible to use the `awesomeplete` library that's used in the page tags box without some significant refactoring because the Pepperminty Wiki core may not request files to be downloaded as extra data.

**Comment by virtadpt** [comment]
onchange?  https://www.w3schools.com/jsref/event_onchange.asp

onselect?  https://www.w3schools.com/jsref/event_onselect.asp

**Comment by sbrl** [comment]
Unfortunately, those aren't quite right @virtadpt.

 - onchange is for `<select>` elements, but I use an `<input type="search" />` with a `<datalist />`
 - onselect is when text is highlighted by the user, not when a `<datalist />` item is selected

**Comment by virtadpt** [comment]
I guess I've just outed myself as a systems engineer and not a web developer?  :)

**Comment by sbrl** [comment]
Not a problem @virtadpt :P

Since there doesn't appear to be a solution to the problem, I'm going to close this for now. However, if anyone discovers a solution in the future, I will gladly implement it :-)
