### ISSUE TITLE
Feature request: Renaming pages

### ISSUE THREAD

**Issue by virtadpt** [sbrl/Pepperminty-Wiki#198]
It is entirely possible that a page can be misnamed due to the workflow for creating a new page (search for a page that doesn't exist, create it, save it).  It should be pretty easy to rename the .md file on disk to rename the page, shouldn't it?

**Comment by sbrl** [comment]
Hey there! Such a feature already exists - though in Pepperminty Wiki it's called _moving_ instead of _renaming_.

Here's a screenshot showing where the button is in the default interface:

![Screenshot_2020-07-16 Main Page - Pepperminty Wiki](https://user-images.githubusercontent.com/9929737/87720951-a03f6400-c7ad-11ea-82a3-31c0f9cd5511.png)

It should be in roughly the same place in all the different themes.

Let me know how you get on :-)

**Comment by sbrl** [comment]
Since I'm pretty sure that the feature you're requesting already exists, I'm going to close this issue now. If you are still experiencing issues, please comment and I'll reopen :-)
