### ISSUE TITLE
Google Sitemaps

### ISSUE THREAD

**Issue by SeanFromIT** [sbrl/Pepperminty-Wiki#207]
Google Search Console (formerly Webmaster Tools) allows website owners to suggest indexing to the search engine via the sitemaps formats defined at [https://www.sitemaps.org/protocol.html](https://www.sitemaps.org/protocol.html). I believe XML or Text would be the best formats for Pepperminty to possibly implement.

**Comment by sbrl** [comment]
Thanks for opening this issue. It looks like the sitemap _has_ to be located on disk at that specific URL. While Pepperminty Wiki _could_, in theory, manage that automatically, I foresee 3 potential issues:

1. Managing a file on disk is inherently more complicated than just serving it to the user - and it adds additional complexity to Pepperminty Wiki
2. If one were to upload an xml file called `sitemap` when Pepperminty Wiki was managing `sitemap.xml` automatically, things would get..... awkward.
3. If one were to create a page called `sitemap.xml` when Pepperminty was managing `sitemap.xml` automatically, things would also get interesting

To this end, it would be much easier to write / append to a `robots.txt` file if it doesn't exist already. This is a bit problematic though, since `robots.txt` must be in the top-level directory (according to [this page](http://www.robotstxt.org/robotstxt.html)) - and Pepperminty Wiki may be installed in a subdirectory - and we don't want to write anything outside our directory if we can help it (we don't currently - this makes Pepperminty Wiki both predictable and easy to backup).

**Comment by sbrl** [comment]
Initial XML sitemap support is now present! Manual setup is required in order for crawlers to notice it though. You need to add the following line to the `robots.txt` file at the _root_ of your domain:

```
Sitemap: https://wiki.example.com/path/to/index.php?action=sitemap
```

So if I had my wiki located at `https://wiki.example.com/subdir/`, I would create (or edit) `robots.txt` at `https://wiki.example.com/robots.txt`.

This manual setup is required because Pepperminty Wiki does not edit _anything_ outside of it's own directory (it's a rule by which I develop it).

If anyone knows of a `<meta />` tag or a HTTP header we could set instead, that would be greatly appreciated.

You can also manually submit the sitemap URL (which can also be found on the credits page) through the web interface of many search engines, which works too.

Finally, if you already have a sitemap, you can use a [sitemap index file](https://www.sitemaps.org/protocol.html#index).

**Comment by sbrl** [comment]
For future reference, I used these pages to help me when implementing this:

 - [Build and submit a sitemap - Search Console Help - Google](https://support.google.com/webmasters/answer/183668?visit_id=637393289607466949-220857521&rd=1)
 - [sitemaps.org - Protocol](https://www.sitemaps.org/protocol.html#index)
