### ISSUE TITLE
Image caption breaks footnotes

### ISSUE THREAD

**Issue by SeanFromIT** [sbrl/Pepperminty-Wiki#209]
Images with captions cause the footnotes to not render (like, the whole `<div class="footnotes">` is missing). Remove ` | caption` from the image, they render. ¯\_(ツ)_/¯

_v0.22-beta1_

**Comment by sbrl** [comment]
Oh my! That's very strange. Do you have some minimal test markdown I can use to debug this please? It's going to require some intensive debugging I think.

**Comment by SeanFromIT** [comment]
https://gist.github.com/SeanFromIT/1b44900aed9df64057fac153f0a2f911

**Comment by sbrl** [comment]
Got it! That was an interesting one. For future reference calling `->text()` when recursively parsing is a _bad idea_: it calls `->textElements()`, which resets `->DefinitionData`, which contains information about footnotes.

This bug was also caused by the templating engine - this has been fixed too.

Due to the complex nature of this bug, if you have any issues relating to this fix please open a new issue and reference this bug in your description.
