### ISSUE TITLE
HTML 500 Error when creating Pepperminty Wiki?

### ISSUE THREAD

**Issue by yuu1412** [sbrl/Pepperminty-Wiki#219]
Hi_!!_
I recently found out about Pepperminty Wiki and am trying it out on my website. I'm new to a lot of the more fiddly coding/website bits but I was able to change my site's php version and made sure that all the extensions are there.
Then I popped the index.php into cpanel, gave it a minute and then tried to navigate to my new wiki to continue configuration.
~~And got an HTML ERROR 500 :(
Before I was getting errors about the peppermint.json file but that was before I fixed the issue with missing extensions. It still didn't work so I scrapped and redid it but now I'm getting the 500 error which is very unhelpful since I don't know what's causing it at all.

Any assistance that can be provided would be great. I'm assuming I messed up somewhere in the initial configuration but no idea what :(~~
nevermind - my site did not like me changing the php type to 7.4, switched back to 7.3, removed the compromised json and it worked

**Comment by sbrl** [comment]
Hey there, @yuu1412! If you're getting an 500 error, then that means you've probably misconfigured your web server. Try checking the server logs. These will be located in `/var/log/nginx/access.log` and `/var/log/nginx/error.log` if you're using Nginx, or `/var/log/apache` if you're running Apache.

Also, `compromised.json` is created when your web server fails the `peppermint.json` access check. `peppermint.json` **must not** be accessible from the web - otherwise your passwords and site secret will be on display for all to see!

**Comment by yuu1412** [comment]
> Hey there, @yuu1412! If you're getting an 500 error, then that means you've probably misconfigured your web server. Try checking the server logs. These will be located in `/var/log/nginx/access.log` and `/var/log/nginx/error.log` if you're using Nginx, or `/var/log/apache` if you're running Apache.
> 
> Also, `compromised.json` is created when your web server fails the `peppermint.json` access check. `peppermint.json` **must not** be accessible from the web - otherwise your passwords and site secret will be on display for all to see!

Hi! I got it working, but there was no way to close my question out (and despite saying it allows markdown the editing i did wasn't working)!

I got it working once I switched php types and edited the permissions of peppermint.json!
Thanks!!

**Comment by sbrl** [comment]
You can close your issue by clicking the "close issue" button. I've clicked it for you here :-)

Glad you got it working! I hope you get on well with Pepperminty Wiki :-)
