### ISSUE TITLE
Congrats and feedback

### ISSUE THREAD

**Issue by felixplesoianu** [sbrl/Pepperminty-Wiki#224]
(I tried to send e-mail but it got returned to sender. Sorry about that.)

Hi there! I just discovered Pepperminty Wiki (thanks to the Awesome Self-Hosted list here on GitHub) and it's great to see that someone else is working on a new wiki engine this side of 2020. Won't be using Pepperminty, because my needs are well-covered right now, but it's another one to keep in mind.

I like that Pepperminty comes as a single PHP file, though it generates a lot of text files during use. I tried using the online downloader, too, but disabling unwanted modules didn't save much space. Use of Markdown is welcome; that the wiki keeps generating revisions forever, not so much. Also, you can keep the database outside the document root... but peppermint.json stays next to index.php and isn't protected in any way by default! Being able to easily customize what the wiki looks like is welcome; that it runs with a ton of warnings on PHP 7.3, not so much. Still useful to have so much functionality in one small package. And hey, at worst it can be used as a personal wiki.

So, congrats, and I hope you'll keep working on it. Good luck in the future!

**Comment by sbrl** [comment]
Thanks!

> though it generates a lot of text files during use.

It does haha. The best workaround for that is customise the [`data_storage_dir`](https://starbeamrainbowlabs.com/labs/peppermint/peppermint-config-info.php#config_data_storage_dir) and point it at a different directory. Lot of text files is the price you may for not using a database :P

> ton of warnings on PHP 7.3, not so much

While [PHP 7.3 is out of support now](https://www.php.net/supported-versions.php), I have a number of fixes that haven't yet been released to fix some issues.

> peppermint.json stays next to index.php and isn't protected in any way by default

Yeah, this is a problem that I've been thinking about for a while. Currently it has a check when you run through the initial setup to make sure that `peppermint.json` is not accessible through your web server - prompting you to block access to it via your web server's config. A better solution is definitely needed though.

> So, congrats, and I hope you'll keep working on it. Good luck in the future!

Thanks! While development has slowed due to many factors, Pepperminty Wiki is a stable and mature piece of software. I use it for multiple important personal wikis myself, so you can be sure that I will continue to develop and work on Pepperminty Wiki.

Thanks again!

Going to close this now, but I can always reopen to discuss further :-)

**Comment by sbrl** [comment]
Oh yeah, and I also have an [Android app](https://github.com/sbrl/Pepperminty-Wiki-Client-Android) that I'vev been working on rewriting :D

**Comment by virtadpt** [comment]
In case anyone's looking for a way to protect `peppermint.json`, here's the .htaccess file I use:

```
<Files "peppermint.json">
    Order Allow,Deny
    Deny from all
</Files>
```

It's nothing fancy but it works.

**Comment by sbrl** [comment]
Cool, thanks @virtadpt! I haven't actually ever set up or configured an Apache server, so thanks! I've updated the getting started docs there to add that: https://github.com/sbrl/Pepperminty-Wiki/blob/master/docs/04-Getting-Started.md#setup-instructions
